name = "slm-agent"
main = "src/worker.ts"
compatibility_date = "2025-09-22"
compatibility_flags = ["nodejs_compat"]

# deploys to *.workers.dev by default

[vars]
APP_NAME = "slm-agent"
USE_GROQ = "1"      # make the edge path use Groq, not Ollama